### ISSUE TITLE
Basic pedestal app not working?

### ISSUE THREAD

**Issue by aivijay** [pedestal/app-tutorial#63]
I just was trying out pedestal with a basic lein project. Tried to access the dev page. Javascript seems to error out as follows:

platform.js:122 Uncaught Invalid match arg: /<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/ilog_exceptions__delegate @ platform.js:122log_exceptions @ platform.js:133process_next_item @ queue.js:26(anonymous function) @ queue.js:32

What am I missing? The project was just generated with 
lein new pedestal-app test-app no-comment

**Comment by aivijay** [comment]
Seems this is too old with ref to the library and this document.

**Comment by ohpauleez** [comment]
Hi @aivijay -
Pedestal App is no longer developed.  Now there is just [Pedestal](https://github.com/pedestal/pedestal) - a set of libraries for writing robust, fast, and secure web services.

**Comment by aivijay** [comment]
Yes, I found that. Thanks.
